### ISSUE TITLE
Why the data bag name "desk1-halfsphere-ic" don't have imu topic?

### ISSUE THREAD

**Issue by Pan-long-ming** [NGCLAB/multi-spectral-dataset#1]
Why the data bag name "desk1-halfsphere-ic" don't have imu topic?

**Comment by weichnn** [comment]
This dataset is proposed for studying multi-spectral motion estimation systems. During the recording, we found that the complex environment was too challenging. So, the IMU is only provided in complex environments to reduce the difficulty.

> Why the data bag name "desk1-halfsphere-ic" don't have imu topic?

**Comment by Pan-long-ming** [comment]
OK, I see
