### ISSUE TITLE
Which type of the data in the topic"/optris/thermal_image (sensor_msgs/Image)" ?

### ISSUE THREAD

**Issue by Pan-long-ming** [NGCLAB/multi-spectral-dataset#2]
Which type of the data in the topic"/optris/thermal_image (sensor_msgs/Image)" ? 
Is it 640x480 16-bit monochrome images in PNG format?

**Comment by weichnn** [comment]
How to extract the data, please check bag_extractor.
https://github.com/weichnn/bag_extractor

**Comment by weichnn** [comment]
Yes, the thermal images are 640x480 16-bit monochrome images. Please check the code in https://github.com/weichnn/bag_extractor for details. @Pan-long-ming
