### ISSUE TITLE
Problem about the groundtruth in the complex environment dataset 

### ISSUE THREAD

**Issue by Pan-long-ming** [NGCLAB/multi-spectral-dataset#3]
I use your dataset named"magistrale-23-night1" and shown the groundtruth in evo,i found that the area range you collected your data have only decimeter,which i think it isn't correspond to the actual situation where you collected dataset.

Can you tell me how to change 16-bit thermal monochrome images into 8-bit thermal monochrome images?

**Comment by weichnn** [comment]
The motion capture is deployed in the room, so there is no groundtruth outside.
