### ISSUE TITLE
Any published material information?

### ISSUE THREAD

**Issue by DreamWaterFound** [NGCLAB/multi-spectral-dataset#5]
In other words, if I wanna cite your excellent work in my paper/report, is there some information that can be used except the link of this repo?

Thanks for reply ;D

**Comment by weichnn** [comment]
Thank you for your attention! This is our paper link: https://ieeexplore.ieee.org/document/9561906/

**Comment by weichnn** [comment]
@DreamWaterFound Thank you for your attention! This is our paper link: https://ieeexplore.ieee.org/document/9561906/

**Comment by DreamWaterFound** [comment]
> @DreamWaterFound Thank you for your attention! This is our paper link: https://ieeexplore.ieee.org/document/9561906/

Thanks for your reply! 👍
