### ISSUE TITLE
Google Drive Link for Thermal-Inertial Dataset

### ISSUE THREAD

**Issue by jonathansel** [NGCLAB/multi-spectral-dataset#7]
Hello, I was wondering if you can provide a google drive link to download the data from the Thermal-Inertial SLAM dataset. I am having trouble using the Baidu Link unfortunately.

**Comment by weichnn** [comment]
Which one sequence cannot be downloaded?

**Comment by jonathansel** [comment]
Sorry for the late reply. Still having trouble but if it would be possible to get the resedential1 sequence on Google Drive I would appreciate it

**Comment by Elkulas** [comment]
> Sorry for the late reply. Still having trouble but if it would be possible to get the resedential1 sequence on Google Drive I would appreciate it

Hi, we are sorry for not providing the Google link and will upload the data you need ASAP.

**Comment by jonathansel** [comment]
Thank you!

**Comment by Elkulas** [comment]
> Thank you!

Hi there, check this link :D
https://drive.google.com/file/d/1LP2rWK9GA9KplCH1AcFUNcf7erhyLX8F/view?usp=sharing

**Comment by jonathansel** [comment]
Awesome thank you so much!
